# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
airos_core_setup:
    resource: "@AirosCoreBundle/Resources/config/setup_routing.yml"
    prefix:   /_setup

airos_core_main:
    resource: "@AirosCoreBundle/Resources/config/main_routing.yml"
